-- CreateEnum
CREATE TYPE "Role" AS ENUM ('SUPER_ADMIN', 'ADMIN', 'PURCHASE', 'BILLING_HEAD', 'BILLING');

-- CreateEnum
CREATE TYPE "OrderStage" AS ENUM ('RAW_INGESTED', 'PENDING', 'REP_ALLOCATION', 'SLIP_GENERATED', 'EXECUTED');

-- CreateEnum
CREATE TYPE "ItemStatus" AS ENUM ('PENDING', 'BILLED', 'NOT_BILLED', 'PARTIALLY_BILLED', 'PRODUCT_CHANGED', 'SUPPLIER_ITEM_DAMAGED', 'SUPPLIER_ITEM_MISSING');

-- AlterTable
ALTER TABLE "order_requests" ADD COLUMN     "stage" "OrderStage" NOT NULL DEFAULT 'RAW_INGESTED';
